import { CheckControl } from '../firewall-store';

export const fortinetControls: CheckControl[] = [
  // Administration
  { id: 'FH-FGT-A01', category: 'Administration', name: 'Admin MFA enabled', description: 'Ensure multi-factor authentication is required for all administrative access.', expectedConfig: 'config system admin -> set two-factor ...', severity: 'HIGH', reference: 'CIS FortiOS 1.1' },
  { id: 'FH-FGT-A02', category: 'Administration', name: 'Admin trusted hosts configured', description: 'Ensure administrative access is restricted to specific trusted IP addresses or subnets.', expectedConfig: 'set trusthost1 x.x.x.x x.x.x.x', severity: 'HIGH', reference: 'CIS FortiOS 1.2' },
  { id: 'FH-FGT-A03', category: 'Administration', name: 'Admin session timeout <= 5 minutes', description: 'Ensure idle administrative sessions are automatically terminated.', expectedConfig: 'config system global -> set admintimeout 5', severity: 'MEDIUM', reference: 'CIS FortiOS 1.3' },
  { id: 'FH-FGT-A04', category: 'Administration', name: 'HTTPS admin access only (no HTTP)', description: 'Ensure administrative access uses strong encryption and cleartext protocols are disabled.', expectedConfig: 'config system interface -> unset allowaccess http', severity: 'HIGH', reference: 'CIS FortiOS 1.4' },
  { id: 'FH-FGT-A05', category: 'Administration', name: 'Default admin account renamed', description: 'Ensure the default "admin" account has been renamed or disabled.', expectedConfig: 'config system admin -> edit newadmin', severity: 'HIGH', reference: 'CIS FortiOS 1.5' },
  { id: 'FH-FGT-A06', category: 'Administration', name: 'Strong password policy enforced', description: 'Ensure complex password requirements are enforced for administrative accounts.', expectedConfig: 'config system password-policy', severity: 'MEDIUM', reference: 'CIS FortiOS 1.6' },
  { id: 'FH-FGT-A07', category: 'Administration', name: 'SSH admin access restricted', description: 'Ensure SSH access is limited or uses strong cryptographic algorithms.', expectedConfig: 'config system interface -> allowaccess ssh', severity: 'MEDIUM', reference: 'CIS FortiOS 1.7' },
  { id: 'FH-FGT-A08', category: 'Administration', name: 'Management interface not exposed to internet', description: 'Ensure management interfaces are not accessible from external, untrusted networks.', expectedConfig: 'Review external interface allowaccess', severity: 'CRITICAL', reference: 'CIS FortiOS 1.8' },

  // Firmware & System
  { id: 'FH-FGT-S01', category: 'Firmware & System', name: 'Firmware is current/supported version', description: 'Ensure the device is running a vendor-supported firmware version with recent security patches.', expectedConfig: 'get system status', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-S02', category: 'Firmware & System', name: 'NTP configured with reliable source', description: 'Ensure Network Time Protocol is configured to synchronize with reliable time sources.', expectedConfig: 'config system ntp', severity: 'LOW', reference: 'Best Practice' },
  { id: 'FH-FGT-S03', category: 'Firmware & System', name: 'System time correct', description: 'Ensure the system time matches the actual current time.', expectedConfig: 'execute time', severity: 'LOW', reference: 'Best Practice' },
  { id: 'FH-FGT-S04', category: 'Firmware & System', name: 'Configuration backup exists and recent', description: 'Ensure the device configuration is backed up securely on a regular basis.', expectedConfig: 'execute backup config ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-S05', category: 'Firmware & System', name: 'HA configured for redundancy', description: 'Ensure High Availability is properly configured to prevent single points of failure.', expectedConfig: 'config system ha', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-S06', category: 'Firmware & System', name: 'DNS configured with secure resolvers', description: 'Ensure DNS resolution uses trusted and secure internal or external servers.', expectedConfig: 'config system dns', severity: 'LOW', reference: 'Best Practice' },

  // Firewall Policies
  { id: 'FH-FGT-P01', category: 'Firewall Policies', name: 'No any/any allow rules', description: 'Ensure there are no overly permissive firewall rules allowing any source to any destination.', expectedConfig: 'Review policies for ANY/ANY/ALL/ACCEPT', severity: 'CRITICAL', reference: 'Best Practice' },
  { id: 'FH-FGT-P02', category: 'Firewall Policies', name: 'All policies have logging enabled', description: 'Ensure traffic matching firewall policies is logged for auditing and incident response.', expectedConfig: 'set logtraffic all/utm', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-P03', category: 'Firewall Policies', name: 'Disabled/unused policies removed', description: 'Ensure firewall rulebase is clean by removing inactive or obsolete rules.', expectedConfig: 'Review disabled policies', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-P04', category: 'Firewall Policies', name: 'Policies applied with least privilege', description: 'Ensure firewall rules adhere to the principle of least privilege, restricting access to necessary resources.', expectedConfig: 'Review policy specificity', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-P05', category: 'Firewall Policies', name: 'No policies allowing risky services (Telnet/FTP) inbound', description: 'Ensure cleartext and historically vulnerable protocols are blocked inbound.', expectedConfig: 'Review inbound services', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-P06', category: 'Firewall Policies', name: 'Internet-facing rules reviewed', description: 'Ensure all internet-exposed services are strictly necessary and adequately secured.', expectedConfig: 'Review WAN-to-LAN rules', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-P07', category: 'Firewall Policies', name: 'Policy ordering optimized', description: 'Ensure most specific rules are placed above more general rules for proper evaluation.', expectedConfig: 'Review policy sequence', severity: 'LOW', reference: 'Best Practice' },
  { id: 'FH-FGT-P08', category: 'Firewall Policies', name: 'NAT configured correctly', description: 'Ensure Network Address Translation is configured securely without exposing internal networks unnecessarily.', expectedConfig: 'Review NAT/VIP settings', severity: 'MEDIUM', reference: 'Best Practice' },

  // Security Profiles
  { id: 'FH-FGT-SP01', category: 'Security Profiles', name: 'Antivirus profile applied to policies', description: 'Ensure Antivirus scanning is enabled on rules permitting file transfers or web traffic.', expectedConfig: 'set av-profile ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-SP02', category: 'Security Profiles', name: 'IPS profile applied to policies', description: 'Ensure Intrusion Prevention System is enabled on all relevant traffic flows.', expectedConfig: 'set ips-sensor ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-SP03', category: 'Security Profiles', name: 'Web Filter enabled', description: 'Ensure Web Filtering is configured to block malicious and inappropriate content.', expectedConfig: 'set webfilter-profile ...', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-SP04', category: 'Security Profiles', name: 'Application Control enabled', description: 'Ensure Application Control is used to restrict unapproved or risky applications.', expectedConfig: 'set application-list ...', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-SP05', category: 'Security Profiles', name: 'SSL Inspection configured', description: 'Ensure encrypted traffic is inspected using Deep Packet Inspection where appropriate.', expectedConfig: 'set ssl-ssh-profile ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-SP06', category: 'Security Profiles', name: 'DNS Filter enabled', description: 'Ensure DNS Filtering is configured to block requests to known malicious domains.', expectedConfig: 'set dnsfilter-profile ...', severity: 'LOW', reference: 'Best Practice' },
  { id: 'FH-FGT-SP07', category: 'Security Profiles', name: 'File Filter configured', description: 'Ensure File Filtering is used to block dangerous file types.', expectedConfig: 'set file-filter-profile ...', severity: 'LOW', reference: 'Best Practice' },

  // VPN
  { id: 'FH-FGT-V01', category: 'VPN', name: 'IPsec uses strong encryption (AES-256)', description: 'Ensure IPsec VPNs use strong cryptographic algorithms like AES-256 for Phase 1 and 2.', expectedConfig: 'set proposal aes256-sha256 ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-V02', category: 'VPN', name: 'SSL VPN MFA enabled', description: 'Ensure multi-factor authentication is required for all remote access VPN users.', expectedConfig: 'config user local ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-V03', category: 'VPN', name: 'VPN split tunneling reviewed', description: 'Ensure split tunneling is disabled unless strictly necessary, to force traffic through firewall inspection.', expectedConfig: 'config vpn ssl web portal ...', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-V04', category: 'VPN', name: 'VPN certificates valid and not self-signed', description: 'Ensure VPN services use valid certificates issued by a trusted Certificate Authority.', expectedConfig: 'set servercert ...', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-V05', category: 'VPN', name: 'VPN access restricted to authorized users', description: 'Ensure VPN access is limited to specific user groups via strict policy controls.', expectedConfig: 'config firewall policy ...', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-V06', category: 'VPN', name: 'VPN tunnel monitoring enabled', description: 'Ensure Dead Peer Detection (DPD) or tunnel monitoring is configured to detect and recover from tunnel failures.', expectedConfig: 'set dpd on-idle', severity: 'LOW', reference: 'Best Practice' },

  // Logging
  { id: 'FH-FGT-L01', category: 'Logging', name: 'Traffic logging enabled on all policies', description: 'Ensure traffic logging is enabled across all policies.', expectedConfig: 'set logtraffic all', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-L02', category: 'Logging', name: 'FortiAnalyzer or Syslog configured', description: 'Ensure logs are forwarded to a central logging server (FortiAnalyzer or Syslog).', expectedConfig: 'config log syslogd setting', severity: 'HIGH', reference: 'Best Practice' },
  { id: 'FH-FGT-L03', category: 'Logging', name: 'Event logging enabled', description: 'Ensure all system and security events are logged locally.', expectedConfig: 'config log eventfilter', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-L04', category: 'Logging', name: 'Log retention policy configured', description: 'Ensure logs are retained for an adequate period to support incident investigation.', expectedConfig: 'config log disk setting', severity: 'MEDIUM', reference: 'Best Practice' },
  { id: 'FH-FGT-L05', category: 'Logging', name: 'Threat logs forwarded to SIEM', description: 'Ensure threat-related logs (IPS, AV, Web Filter) are forwarded to a SIEM for analysis.', expectedConfig: 'config log syslogd filter', severity: 'MEDIUM', reference: 'Best Practice' },
];
